In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [5]:
print ('1D array')
a = np.array([1,2,3,4,5])
print (a)

print ('2D array')
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print (b)

print ('3D array')
c = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print (c)

1D array
[1 2 3 4 5]
2D array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [6]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [7]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [8]:
print(c.dtype)

int64


In [9]:
import numpy as np
matrix = np.array([[1,2,3,4,5],[6,7,8,9,10]])
transpose_mat = np.transpose(matrix)
transpose_mat2 = matrix.T
print("Original matrix\n", matrix)
print("\nTransposed matrix :\n",transpose_mat) 
print("\nTransposed matrix2 :\n",transpose_mat2) 

Original matrix
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Transposed matrix :
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]

Transposed matrix2 :
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [10]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
c = a+b
print(c)

[ 2  4  6  8 10]


In [12]:
x = np.ones((6), dtype = int)
x

array([1, 1, 1, 1, 1, 1])

In [13]:
z = np.zeros((5,6), dtype = int)
z

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [16]:
a= np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [18]:
a=np.arange(1,31,2)
print(a)
b=np.arange(2,31,2)
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [21]:
a = a.reshape(3,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [24]:
a=np.arange(0,18)
b=np.arange(20,38)
c=a+b
c= c.reshape(6,3)
c

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])